/**
 * scala-play-template
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package sttawm.client.api

import sttawm.client.model.PingResponseApiResponse
import sttawm.client.core._
import sttawm.client.core.CollectionFormats._
import sttawm.client.core.ApiKeyLocations._

object PingApi {

  def apply(baseUrl: String = "http://localhost:9000") = new PingApi(baseUrl)
}

class PingApi(baseUrl: String) {

  /**
   * Expected answers:
   *   code 200 : PingResponseApiResponse 
   */
  def ping(): ApiRequest[PingResponseApiResponse] =
    ApiRequest[PingResponseApiResponse](ApiMethods.GET, baseUrl, "/ping", "application/json")
      .withSuccessResponse[PingResponseApiResponse](200)
      



}

